services:
  notifier-service:
    build:
      context: ./src/notifier-service
      dockerfile: Dockerfile
    env_file:
      - src/notifier-service/.env
    ports:
      - ${PORT_NOTIFIER}
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
